"""Add resolution logic fields

Revision ID: 20df69e5fe98
Revises: 005_day5_declaration_extraction
Create Date: 2026-09-10 23:04:31.960779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20df69e5fe98'
down_revision: Union[str, None] = '005_day5_declaration_extraction'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_findings', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PASS', 'FAIL', 'REVIEW', 'NOT_APPLICABLE', name='compliance_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('compliance_findings', 'reason_code',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('MRP_PRESENT', 'MRP_MISSING', 'MRP_INVALID_FORMAT', 'MRP_LOW_CONFIDENCE', 'NET_QUANTITY_PRESENT', 'NET_QUANTITY_MISSING', 'NET_QUANTITY_INVALID_UNIT', 'NET_QUANTITY_LOW_CONFIDENCE', 'MANUFACTURER_PRESENT', 'MANUFACTURER_INCOMPLETE', 'MANUFACTURER_MISSING', 'PACKER_PRESENT', 'IMPORTER_PRESENT', 'DATE_VALID', 'DATE_MISSING', 'CONSUMER_CARE_COMPLETE', 'CONSUMER_CARE_INCOMPLETE', 'COUNTRY_ORIGIN_PRESENT', 'COUNTRY_ORIGIN_MISSING', 'COMMODITY_NAME_PRESENT', 'COMMODITY_NAME_MISSING', 'MANUAL_REVIEW_TRIGGERED', 'GENERAL_PASS', 'GENERAL_FAIL', name='reason_code_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('compliance_rules', 'declaration_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MRP', 'NET_QUANTITY', 'MANUFACTURER', 'MANUFACTURER_NAME', 'MANUFACTURER_ADDRESS', 'PACKER', 'PACKER_NAME', 'PACKER_ADDRESS', 'IMPORTER', 'IMPORTER_NAME', 'IMPORTER_ADDRESS', 'MARKETER', 'MARKETER_NAME', 'MARKETER_ADDRESS', 'COUNTRY_OF_ORIGIN', 'COMMODITY_NAME', 'DATE_OF_MANUFACTURE', 'MANUFACTURE_DATE', 'DATE_OF_PACKING', 'PACKING_DATE', 'DATE_OF_IMPORT', 'IMPORT_DATE', 'BEST_BEFORE', 'EXPIRY_DATE', 'CONSUMER_CARE_PHONE', 'CONSUMER_CARE_EMAIL', 'CONSUMER_CARE_ADDRESS', 'BATCH_OR_LOT_NUMBER', 'UNKNOWN', 'OTHER', name='declaration_type_rule_enum', native_enum=False),
               existing_nullable=True)
    op.alter_column('compliance_rules', 'severity',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='rule_severity_enum', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_compliance_rules_declaration_type'), 'compliance_rules', ['declaration_type'], unique=False)
    op.drop_index(op.f('ix_declaration_ocr_blocks_declaration_id'), table_name='declaration_ocr_blocks')
    op.drop_index(op.f('ix_declaration_ocr_blocks_ocr_block_id'), table_name='declaration_ocr_blocks')
    op.add_column('declarations', sa.Column('resolution_status', sa.Enum('AUTO_RESOLVED', 'NEEDS_REVIEW', 'CONFLICT', 'NOT_DETECTED', 'CONFIRMED', 'REJECTED', name='resolution_status_enum', native_enum=False), server_default='NOT_DETECTED', nullable=False))
    op.add_column('declarations', sa.Column('resolution_reason', sa.Text(), nullable=True))
    op.add_column('declarations', sa.Column('canonical_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('declarations', sa.Column('candidate_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.alter_column('declarations', 'declaration_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MRP', 'NET_QUANTITY', 'MANUFACTURER', 'MANUFACTURER_NAME', 'MANUFACTURER_ADDRESS', 'PACKER', 'PACKER_NAME', 'PACKER_ADDRESS', 'IMPORTER', 'IMPORTER_NAME', 'IMPORTER_ADDRESS', 'MARKETER', 'MARKETER_NAME', 'MARKETER_ADDRESS', 'COUNTRY_OF_ORIGIN', 'COMMODITY_NAME', 'DATE_OF_MANUFACTURE', 'MANUFACTURE_DATE', 'DATE_OF_PACKING', 'PACKING_DATE', 'DATE_OF_IMPORT', 'IMPORT_DATE', 'BEST_BEFORE', 'EXPIRY_DATE', 'CONSUMER_CARE_PHONE', 'CONSUMER_CARE_EMAIL', 'CONSUMER_CARE_ADDRESS', 'BATCH_OR_LOT_NUMBER', 'UNKNOWN', 'OTHER', name='declaration_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('declarations', 'confidence_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.drop_index(op.f('ix_declarations_review_status'), table_name='declarations')
    op.create_index(op.f('ix_declarations_resolution_status'), 'declarations', ['resolution_status'], unique=False)
    op.drop_column('declarations', 'review_status')
    op.alter_column('image_quality_metrics', 'quality_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACCEPTED', 'RECAPTURE_RECOMMENDED', 'REVIEW', name='image_quality_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ACCEPTED'::character varying"))
    op.drop_constraint(op.f('uq_image_quality_scan_image_id'), 'image_quality_metrics', type_='unique')
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('DRAFT', 'GENERATED', 'ARCHIVED', name='report_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('scan_images', 'image_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FRONT', 'BACK', 'SIDE', 'TOP', 'BOTTOM', 'OTHER', name='image_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('scan_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CREATED', 'IMAGES_UPLOADED', 'PROCESSING', 'OCR_COMPLETED', 'DECLARATIONS_EXTRACTED', 'COMPLIANCE_EVALUATED', 'REVIEW_REQUIRED', 'COMPLETED', 'FAILED', name='scan_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'INSPECTOR', 'REVIEWER', name='user_role_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'INSPECTOR', 'REVIEWER', name='user_role_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('scan_sessions', 'status',
               existing_type=sa.Enum('CREATED', 'IMAGES_UPLOADED', 'PROCESSING', 'OCR_COMPLETED', 'DECLARATIONS_EXTRACTED', 'COMPLIANCE_EVALUATED', 'REVIEW_REQUIRED', 'COMPLETED', 'FAILED', name='scan_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('scan_images', 'image_type',
               existing_type=sa.Enum('FRONT', 'BACK', 'SIDE', 'TOP', 'BOTTOM', 'OTHER', name='image_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('DRAFT', 'GENERATED', 'ARCHIVED', name='report_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_image_quality_scan_image_id'), 'image_quality_metrics', ['scan_image_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('image_quality_metrics', 'quality_status',
               existing_type=sa.Enum('ACCEPTED', 'RECAPTURE_RECOMMENDED', 'REVIEW', name='image_quality_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'ACCEPTED'::character varying"))
    op.add_column('declarations', sa.Column('review_status', sa.VARCHAR(length=30), server_default=sa.text("'UNREVIEWED'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_declarations_resolution_status'), table_name='declarations')
    op.create_index(op.f('ix_declarations_review_status'), 'declarations', ['review_status'], unique=False)
    op.alter_column('declarations', 'confidence_level',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('declarations', 'declaration_type',
               existing_type=sa.Enum('MRP', 'NET_QUANTITY', 'MANUFACTURER', 'MANUFACTURER_NAME', 'MANUFACTURER_ADDRESS', 'PACKER', 'PACKER_NAME', 'PACKER_ADDRESS', 'IMPORTER', 'IMPORTER_NAME', 'IMPORTER_ADDRESS', 'MARKETER', 'MARKETER_NAME', 'MARKETER_ADDRESS', 'COUNTRY_OF_ORIGIN', 'COMMODITY_NAME', 'DATE_OF_MANUFACTURE', 'MANUFACTURE_DATE', 'DATE_OF_PACKING', 'PACKING_DATE', 'DATE_OF_IMPORT', 'IMPORT_DATE', 'BEST_BEFORE', 'EXPIRY_DATE', 'CONSUMER_CARE_PHONE', 'CONSUMER_CARE_EMAIL', 'CONSUMER_CARE_ADDRESS', 'BATCH_OR_LOT_NUMBER', 'UNKNOWN', 'OTHER', name='declaration_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('declarations', 'candidate_details')
    op.drop_column('declarations', 'canonical_value')
    op.drop_column('declarations', 'resolution_reason')
    op.drop_column('declarations', 'resolution_status')
    op.create_index(op.f('ix_declaration_ocr_blocks_ocr_block_id'), 'declaration_ocr_blocks', ['ocr_block_id'], unique=False)
    op.create_index(op.f('ix_declaration_ocr_blocks_declaration_id'), 'declaration_ocr_blocks', ['declaration_id'], unique=False)
    op.drop_index(op.f('ix_compliance_rules_declaration_type'), table_name='compliance_rules')
    op.alter_column('compliance_rules', 'severity',
               existing_type=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='rule_severity_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('compliance_rules', 'declaration_type',
               existing_type=sa.Enum('MRP', 'NET_QUANTITY', 'MANUFACTURER', 'MANUFACTURER_NAME', 'MANUFACTURER_ADDRESS', 'PACKER', 'PACKER_NAME', 'PACKER_ADDRESS', 'IMPORTER', 'IMPORTER_NAME', 'IMPORTER_ADDRESS', 'MARKETER', 'MARKETER_NAME', 'MARKETER_ADDRESS', 'COUNTRY_OF_ORIGIN', 'COMMODITY_NAME', 'DATE_OF_MANUFACTURE', 'MANUFACTURE_DATE', 'DATE_OF_PACKING', 'PACKING_DATE', 'DATE_OF_IMPORT', 'IMPORT_DATE', 'BEST_BEFORE', 'EXPIRY_DATE', 'CONSUMER_CARE_PHONE', 'CONSUMER_CARE_EMAIL', 'CONSUMER_CARE_ADDRESS', 'BATCH_OR_LOT_NUMBER', 'UNKNOWN', 'OTHER', name='declaration_type_rule_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('compliance_findings', 'reason_code',
               existing_type=sa.Enum('MRP_PRESENT', 'MRP_MISSING', 'MRP_INVALID_FORMAT', 'MRP_LOW_CONFIDENCE', 'NET_QUANTITY_PRESENT', 'NET_QUANTITY_MISSING', 'NET_QUANTITY_INVALID_UNIT', 'NET_QUANTITY_LOW_CONFIDENCE', 'MANUFACTURER_PRESENT', 'MANUFACTURER_INCOMPLETE', 'MANUFACTURER_MISSING', 'PACKER_PRESENT', 'IMPORTER_PRESENT', 'DATE_VALID', 'DATE_MISSING', 'CONSUMER_CARE_COMPLETE', 'CONSUMER_CARE_INCOMPLETE', 'COUNTRY_ORIGIN_PRESENT', 'COUNTRY_ORIGIN_MISSING', 'COMMODITY_NAME_PRESENT', 'COMMODITY_NAME_MISSING', 'MANUAL_REVIEW_TRIGGERED', 'GENERAL_PASS', 'GENERAL_FAIL', name='reason_code_enum', native_enum=False),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('compliance_findings', 'status',
               existing_type=sa.Enum('PASS', 'FAIL', 'REVIEW', 'NOT_APPLICABLE', name='compliance_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
