import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    INSPECTOR = "INSPECTOR"
    REVIEWER = "REVIEWER"


class ScanStatus(str, enum.Enum):
    CREATED = "CREATED"
    IMAGES_UPLOADED = "IMAGES_UPLOADED"
    PROCESSING = "PROCESSING"
    OCR_COMPLETED = "OCR_COMPLETED"
    DECLARATIONS_EXTRACTED = "DECLARATIONS_EXTRACTED"
    COMPLIANCE_EVALUATED = "COMPLIANCE_EVALUATED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ImageType(str, enum.Enum):
    FRONT = "FRONT"
    BACK = "BACK"
    SIDE = "SIDE"
    TOP = "TOP"
    BOTTOM = "BOTTOM"
    OTHER = "OTHER"


class DeclarationType(str, enum.Enum):
    MRP = "MRP"
    NET_QUANTITY = "NET_QUANTITY"
    MANUFACTURER = "MANUFACTURER"
    MANUFACTURER_NAME = "MANUFACTURER_NAME"
    MANUFACTURER_ADDRESS = "MANUFACTURER_ADDRESS"
    PACKER = "PACKER"
    PACKER_NAME = "PACKER_NAME"
    PACKER_ADDRESS = "PACKER_ADDRESS"
    IMPORTER = "IMPORTER"
    IMPORTER_NAME = "IMPORTER_NAME"
    IMPORTER_ADDRESS = "IMPORTER_ADDRESS"
    COUNTRY_OF_ORIGIN = "COUNTRY_OF_ORIGIN"
    COMMODITY_NAME = "COMMODITY_NAME"
    DATE_OF_MANUFACTURE = "DATE_OF_MANUFACTURE"
    MANUFACTURE_DATE = "MANUFACTURE_DATE"
    DATE_OF_PACKING = "DATE_OF_PACKING"
    PACKING_DATE = "PACKING_DATE"
    DATE_OF_IMPORT = "DATE_OF_IMPORT"
    IMPORT_DATE = "IMPORT_DATE"
    BEST_BEFORE = "BEST_BEFORE"
    EXPIRY_DATE = "EXPIRY_DATE"
    CONSUMER_CARE_PHONE = "CONSUMER_CARE_PHONE"
    CONSUMER_CARE_EMAIL = "CONSUMER_CARE_EMAIL"
    CONSUMER_CARE_ADDRESS = "CONSUMER_CARE_ADDRESS"
    BATCH_OR_LOT_NUMBER = "BATCH_OR_LOT_NUMBER"
    UNKNOWN = "UNKNOWN"
    OTHER = "OTHER"


class ReviewStatus(str, enum.Enum):
    UNREVIEWED = "UNREVIEWED"
    CONFIRMED = "CONFIRMED"
    CORRECTED = "CORRECTED"
    REJECTED = "REJECTED"


class ConfidenceLevel(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class RuleSeverity(str, enum.Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ComplianceStatus(str, enum.Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    REVIEW = "REVIEW"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ReasonCode(str, enum.Enum):
    MRP_PRESENT = "MRP_PRESENT"
    MRP_MISSING = "MRP_MISSING"
    MRP_INVALID_FORMAT = "MRP_INVALID_FORMAT"
    MRP_LOW_CONFIDENCE = "MRP_LOW_CONFIDENCE"
    NET_QUANTITY_PRESENT = "NET_QUANTITY_PRESENT"
    NET_QUANTITY_MISSING = "NET_QUANTITY_MISSING"
    NET_QUANTITY_INVALID_UNIT = "NET_QUANTITY_INVALID_UNIT"
    NET_QUANTITY_LOW_CONFIDENCE = "NET_QUANTITY_LOW_CONFIDENCE"
    MANUFACTURER_PRESENT = "MANUFACTURER_PRESENT"
    MANUFACTURER_INCOMPLETE = "MANUFACTURER_INCOMPLETE"
    MANUFACTURER_MISSING = "MANUFACTURER_MISSING"
    PACKER_PRESENT = "PACKER_PRESENT"
    IMPORTER_PRESENT = "IMPORTER_PRESENT"
    DATE_VALID = "DATE_VALID"
    DATE_MISSING = "DATE_MISSING"
    CONSUMER_CARE_COMPLETE = "CONSUMER_CARE_COMPLETE"
    CONSUMER_CARE_INCOMPLETE = "CONSUMER_CARE_INCOMPLETE"
    COUNTRY_ORIGIN_PRESENT = "COUNTRY_ORIGIN_PRESENT"
    COUNTRY_ORIGIN_MISSING = "COUNTRY_ORIGIN_MISSING"
    COMMODITY_NAME_PRESENT = "COMMODITY_NAME_PRESENT"
    COMMODITY_NAME_MISSING = "COMMODITY_NAME_MISSING"
    MANUAL_REVIEW_TRIGGERED = "MANUAL_REVIEW_TRIGGERED"
    GENERAL_PASS = "GENERAL_PASS"
    GENERAL_FAIL = "GENERAL_FAIL"


class ImageQualityStatus(str, enum.Enum):
    ACCEPTED = "ACCEPTED"
    RECAPTURE_RECOMMENDED = "RECAPTURE_RECOMMENDED"
    REVIEW = "REVIEW"


class ImageQualityWarning(str, enum.Enum):
    BLUR = "BLUR"
    GLARE = "GLARE"
    LOW_RESOLUTION = "LOW_RESOLUTION"
    ROTATED = "ROTATED"
    UNREADABLE_REGION = "UNREADABLE_REGION"
    CROPPED = "CROPPED"


class ImageProcessingStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    RECAPTURE_RECOMMENDED = "RECAPTURE_RECOMMENDED"
    FAILED = "FAILED"


class ReportStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    ARCHIVED = "ARCHIVED"


class RuleType(str, enum.Enum):
    PRESENCE = "presence"
    SYNTAX = "syntax"
    VALUE_RANGE = "value_range"
    CONDITIONAL = "conditional"
    MULTI_DECLARATION = "multi_declaration"
